package com.medistock.service;

import jakarta.annotation.PostConstruct;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import java.util.Map;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

@Slf4j
@Service
public class EmailService {

    private final JavaMailSender mailSender;

    public EmailService(JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    @Value("${app.mail.enabled:false}")
    private boolean enabled;

    @Value("${app.mail.from:no-reply@medistock.local}")
    private String fromAddress;

    @Value("${medistock.notification.admin-email:${app.mail.admin-address:}}")
    private String adminAddress;

    @Value("${spring.mail.host:}")
    private String mailHost;

    @Value("${spring.mail.port:}")
    private String mailPort;

    @Value("${spring.mail.username:}")
    private String mailUsername;

    @Value("${spring.mail.properties.mail.smtp.auth:false}")
    private String smtpAuth;

    @Value("${spring.mail.properties.mail.smtp.starttls.enable:false}")
    private String startTlsEnabled;

    @PostConstruct
    void logMailConfiguration() {
        log.info(
                "JavaMailSender initialized. host={}, port={}, usernameConfigured={}, smtpAuth={}, startTls={}, adminEmailConfigured={}, enabled={}",
                blankToUnset(mailHost),
                blankToUnset(mailPort),
                mailUsername != null && !mailUsername.isBlank(),
                smtpAuth,
                startTlsEnabled,
                adminAddress != null && !adminAddress.isBlank(),
                enabled
        );
    }

    public boolean sendAdminEventEmail(String eventName, Map<String, String> details) {
        log.info("EmailService invoked for MediStock administrator email event '{}'", eventName);
        if (!enabled) {
            log.info("Skipping MediStock administrator email for event '{}' because app.mail.enabled=false", eventName);
            return false;
        }
        if (adminAddress == null || adminAddress.isBlank()) {
            log.warn("Skipping MediStock email because no administrator email is configured");
            return false;
        }
        try {
            log.info("Generating MediStock HTML email for event '{}'", eventName);
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");
            helper.setFrom(fromAddress);
            helper.setTo(adminAddress.trim());
            helper.setSubject("[MediStock] " + eventName);
            helper.setText(renderHtml(eventName, details), true);
            log.info("Executing JavaMailSender.send() for MediStock event '{}'", eventName);
            mailSender.send(message);
            log.info("Sent MediStock administrator email for event '{}' to {}", eventName, adminAddress.trim());
            return true;
        } catch (MessagingException | RuntimeException ex) {
            throw new IllegalStateException("Unable to send MediStock email for event " + eventName, ex);
        }
    }

    private String renderHtml(String title, Map<String, String> details) {
        StringBuilder rows = new StringBuilder();
        details.forEach((key, value) -> rows.append("<tr>")
                .append("<td style=\"padding:12px;color:#475569;font-weight:700;border-bottom:1px solid #e2e8f0;width:42%;vertical-align:top;\">")
                .append(escape(key))
                .append("</td><td style=\"padding:12px;color:#0b1f33;border-bottom:1px solid #e2e8f0;word-break:break-word;\">")
                .append(renderValue(key, value))
                .append("</td></tr>"));
        return """
                <div style="font-family:Inter,Arial,sans-serif;background:#f5faf8;padding:24px;">
                  <div style="max-width:640px;margin:0 auto;background:#ffffff;border:1px solid #dbe7e2;border-radius:8px;overflow:hidden;">
                    <div style="background:#0b1f33;color:#ffffff;padding:22px 24px;">
                      <div style="font-size:13px;text-transform:uppercase;color:#6ee7b7;">MediStock</div>
                      <h1 style="margin:8px 0 0;font-size:22px;line-height:1.25;">%s</h1>
                    </div>
                    <table style="width:100%%;border-collapse:collapse;">%s</table>
                    <div style="padding:16px 24px;color:#64748b;font-size:12px;line-height:1.5;">This automated alert was generated by MediStock inventory monitoring.</div>
                  </div>
                </div>
                """.formatted(escape(title), rows);
    }

    private String renderValue(String key, String value) {
        if ("Direct Link".equals(key) && value != null && !value.isBlank() && !"Not applicable".equals(value)) {
            String escaped = escape(value);
            return "<a href=\"" + escaped + "\" style=\"color:#047857;font-weight:700;\">" + escaped + "</a>";
        }
        return escape(value);
    }

    private String escape(String value) {
        if (value == null) {
            return "";
        }
        return value
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;");
    }

    private String blankToUnset(String value) {
        return value == null || value.isBlank() ? "<unset>" : value;
    }
}
