# ==========================================
# MediStock - Application Configuration
# ==========================================

# ------------------------------------------
# Server Configuration
# ------------------------------------------
server.port=8082


# ------------------------------------------
# PostgreSQL Database Configuration
# ------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/medistock_db
spring.datasource.username=postgres
spring.datasource.password=Aishu@17

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver


# ------------------------------------------
# JPA / Hibernate Configuration
# ------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ------------------------------------------
# Fast2SMS Configuration
# ------------------------------------------
fast2sms.api.key=oJCb0OzpKE3ie5nUS9gmtBc2xY6f7r841XklRaTIsGMjuZhQDNdFPnVK6q5RLwx8J3fOi2GtN4SyIlgm


# ------------------------------------------
# Admin Security
# ------------------------------------------
admin.secret.id=ADMIN@2026


# ------------------------------------------
# Pharmacist Security
# ------------------------------------------
pharmacist.secret.code=PHARMA@2026


# ------------------------------------------
# Staff Security
# ------------------------------------------
staff.secret.code=STAFF@2026
# ==========================================
# EMAIL CONFIGURATION
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aishupatlolla19@gmail.com
spring.mail.password=zutu wznw pyhe zzbz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true