spring.application.name=medistock-backend
server.port=8080

spring.profiles.active=dev

app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

app.jwt.secret=ChangeThisSecretKeyToSomethingLongAndRandomForProduction123456
app.jwt.expiration-ms=86400000

# EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ushalalitha9393@gmail.com
spring.mail.password=wfckwuspwtjarneg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.notifications.email.enabled=true
app.notifications.email.to=ushalalitha9393@gmail.com

app.inventory.low-stock-threshold=20
app.inventory.expiry-warning-days=30

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
